plugins/statsd/CMakeLists.txt, plugins/statsd/NWNXStatsd.cpp, plugins/statsd/NWNXStatsd.h, plugins/statsd/README.md, plugins/statsd/nwnx_statsd.nss, plugins/statsd/plugin-statsd.cpp, plugins/statsd/statsd_client.cpp, plugins/statsd/statsd_client.h
As the subject says. Can be used to make pretty pictures.
If you don't know what statsd is, there is a README.md introducing it.
=> plugins/statsd: simple plugin to send data to a statsd server

CMakeModules/FindMHASH.cmake, plugins/mhash/CMakeLists.txt, plugins/mhash/NWNXMHash.cpp, plugins/mhash/NWNXMHash.h, plugins/mhash/README.md, plugins/mhash/nwnx_mhash.nss, plugins/mhash/plugin-mhash.cpp
As the subject says. README in the box.
Might be useful to someone.
=> plugins/mhash: simple wrapper around libmhash

plugins/chat/HookChat.cpp
As the subject says, supports sending single messages for PRIVATE and SERVER mode.
=> plugins/chat: support private and server in SendMsgSingle()

plugins/profiler/HookRunScript.cpp, plugins/profiler/NWNXProfiler.cpp, plugins/profiler/nwnx_profiler.nss
/* run.nss */
void main()
{
GetRunningScriptName() => "run"
}
=> plugins/profiler: add nwn calls for getting the script name & callstack of the current script

plugins/mhash/NWNXMHash.cpp, plugins/mhash/NWNXMHash.h, plugins/mhash/nwnx_mhash.nss
This adds mcrypt KEYGEN support. Might be of use to some.
=> plugins/mhash: support mcrypt-keygen

newpluginapi.h, nwnx2lib.cpp
=> pluginlink: fix NotifyEventHooksNotAboortable not having a valid address

gline.h, plugins/statsd/NWNXStatsd.cpp, plugins/statsd/NWNXStatsd.h
* Fix couple of places in statsd that didn't specify namespace.
=> gline: Remove using namespace std; from global header.

plugins/jvm/NWNXJVM.cpp, plugins/jvm/java/src/org/nwnx/nwnx2/jvm/ResMan.java, plugins/jvm/java/src/org/nwnx/nwnx2/jvm/ResManListener.java
Haven't tested running it, since I don't have a jvm stack anymore.
But hey, it compiles, and looks about right!
=> plugins/jvm: make it compile against new resman semantics

include/nwn_const.h
* Add missing constants.
* Fix incorrect OBJECT_TYPE_PLACEABLE.
=> core: Update OBJECT_TYPE_* constants.

plugins/vaultster/client.cpp, plugins/vaultster/vaultster-serv.cpp
=> plugins/vaultster: fix namespace ambiguity in c++11

plugins/chat/HookChat.cpp
client->AsNWSPlayer() doesn't mean what I thought it meant.
=> plugins/chat: Fix broken CCMessage hook.

plugins/connect/ConnectHooks.cpp, plugins/connect/NWNXConnect.cpp, plugins/connect/NWNXConnect.h, plugins/connect/pluginlink.h
See pluginlink.h for docs.
Plz review
=> plugins/connect: events for OnPlayerConnect/Disconnect(Before/After)

plugins/serverlist/NWNXServerlist.cpp
Very small chance this could ruin someones day.  But might as well change it.
=> plugins/serverlist: Update confKey

plugins/mhash/nwnx_mhash.nss
=> plugins/mhash: add missing function implementation for uuid()

api/CNWSCreatureStats_ClassInfo.h
See label on bottom for expiry.
=> api/CreatureStats: complete ClassInfo

api/CServerExoApp.cpp, api/CServerExoApp.h
because life is too short for explicit casting
=> api: fix some accessor ret types in CServerExoApp

core/events/Console.cpp
Small niggle-amend: Makes adding NWNX stuff to status prettier.
=> core/Console: run "status" before nwnx code as well, just like "help"

core/events/Console_Builtins.cpp, lib/nwn_hooks.c, modules.c, nwnx2lib.cpp, override/openoverride/openoverride.h, plugins/defenses/NWNXDefenses.cpp, plugins/gperf_gen.sh, plugins/lua/NWNXLua.cpp, plugins/spells/NWNXSpells.cpp, plugins/structs/NWNXStructs.cpp, plugins/system/NWNXSystem.cpp, plugins/tweaks/NWNXTweaks.cpp, plugins/weapons/NWNXWeapons.cpp
Mainly field initializer lists.
One NULL -> int return value.
Few other small issues.
=> Fix some of the warnings from new C(XX) flags.

api/nwndef.h, typedef.h
Add header to nwndef.h
Change type uint32_t -> unsigned long
=> api: nwobjid not visible in api

include/structs/CGameEffect.h, plugins/structs/CMakeLists.txt, plugins/structs/NWNXStructs.h, plugins/structs/StructsStrCmds.gperf, plugins/structs/funcs/f_GetCasterLevel.c, plugins/structs/nwnx_structs.nss
modified:   ../../include/structs/CGameEffect.h
modified:   CMakeLists.txt
modified:   NWNXStructs.h
modified:   StructsStrCmds.gperf
modified:   nwnx_structs.nss
new file:   funcs/f_GetCasterLevel.c
=> add GetEffectCasterLevel() to nwnx_structs

plugins/resman/CMakeLists.txt, plugins/resman/NWNXResMan.cpp, plugins/resman/OnRequest.cpp, plugins/resman/nwnx_resman.nss
Exposes ExoResMan->GetKeyEntry, which can be used to check resref existence
=> plugins/resman: expose Exists/GetKeyEntry to nwscript

include/structs/CNWSCreature.h, plugins/funcs/CMakeLists.txt, plugins/funcs/FuncsStrCmds.gperf, plugins/funcs/NWNXFuncs.h, plugins/funcs/funcs/other/f_GetNormalAppearance.c, plugins/funcs/funcs/other/f_GetNormalRace.c, plugins/funcs/nwnx_funcs.nss
- new files: funcs/other/f_GetNormalAppearance.c, funcs/other/f_GetNormalRace.c
- updated include/structs/CNWSCreature.h to name and comment fields used.
=> added GetNormalAppearance() and GetNormalRace() to nwnx_funcs.

plugins/damage/CMakeLists.txt
Simple copy/paste error, but breaks compile
=> fix damage/CMakeLists.txt
