- plugins/resman/NWNXResMan.cpp
Resman would fail for 16 chars long resrefs due to snprintf cutting it off with
a \0.
> plugins/resman: fix resman not returning 16 chars long resrefs

- CMakeLists.txt
- compile.sh
- plugins/defenses/CMakeLists.txt
- plugins/funcs/CMakeLists.txt
- plugins/spells/CMakeLists.txt
- plugins/structs/CMakeLists.txt
- plugins/system/CMakeLists.txt
- plugins/tweaks/CMakeLists.txt
- plugins/weapons/CMakeLists.txt
This doesn't change anything for those who want to build in
the source tree or have any impact on the auto tools build
system.
- Add fake target to always rebuild compiled directory.
- Modify gperf commands to add an additional parameter for their
target name and update all CMakeLists.txt for plugins that use gperf.
- Move all compile.sh functionality possible to CMakeLists.txt.
> Update cmake build to support out of source tree builds.

- include/nx_hook.h
This is just to remove the need for user specified casts.
> nx_hook: Add utility macro.

- newpluginapi.h
Another stupid mistake that could have been prevented with a testing framework.
> pluginlink: fix broken macro for CallService() in plugins

- plugins/statsd/NWNXStatsd.cpp
Fixes a memleak every time statsd events are sent through.
> plugins/statsd: fix memleaks when sending data to statsd

- gline.cpp
- plugins/defenses/funcs/f_GetDefenseOption.c
- plugins/defenses/funcs/f_SetDefenseOption.c
- plugins/events/HookFunc.cpp
- plugins/events/NWNXEvents.h
- plugins/extend/Hooks.cpp
- plugins/fixes/FixesHooks.cpp
- plugins/funcsext/NWNXFuncsExt.cpp
- plugins/odmbc/NWNXodbc.cpp
- plugins/serverlist/ServerlistHooks.cpp
- plugins/spells/funcs/f_GetSpellOption.c
- plugins/spells/funcs/f_SetSpellOption.c
- plugins/tweaks/funcs/f_GetTweakOption.c
- plugins/tweaks/funcs/f_SetTweakOption.c
Nothing that will potentially be replaced by 2.8 api has been changed.
* gline: Remove a couple unused variables.  There are still unsigned/signed
issues here, but I'm not going to risk breaking anything.
* plugins/defenses, spells, tweaks: Fix argument to 'sizeof' in 'snprintf'
using the size of char * rather than the size of the destination string.
It works, but is a warning and there is no benefit to it.
* plugins/serverlist: Fix missing return value in HookFunctions.  Doesn't
really need one, but might as well return something.
* plugins/fixes and events: Fix unsigned/signed comparison warnings.
* plugins/funcext: Fix a handle of sprintfs that are just setting string
length to zero.
* plugins/odmbc: Clarify a boolean expression with parens.  Fix an int
being initialized with NULL.
> Fix some warnings.

- plugins/structs/CMakeLists.txt
- plugins/structs/NWNXStructs.h
- plugins/structs/StructsStrCmds.gperf
- plugins/structs/funcs/f_GetInteger.c
- plugins/structs/funcs/f_GetNumIntegers.c
- plugins/structs/nwnx_structs.nss
Plugin assumes 16 effect integers by default, which is wrong. Functions
would also allow writing over the array length with no checks, clobbering
the CGameEffect* struct and whatever else follows.
This patch adds GetEffectNumIntegers() to retrieve the array size and adds
safeguards to prevent clobbering the stack.
Please review before merging.
> plugins/structs: add GetEffectNumIntegers(), fix possible mem clobbering

- plugins/events/HookFunc.cpp
- plugins/events/HookFunc.h
- plugins/events/NWNXEvents.cpp
This now can be done due to the dtor fix applied to 2.8.
Please review before merging.
I've completely removed the RunScript wrapper, seemed really unneccessary.
> plugins/events: fix memleak each time when calling into nwscript

- api/CScriptLocation.h
- api/nwnstructs.h
This used to be okay, but breaks on gcc >= 4.9.2 (jessie). Numbers
are mangled when casting so incorrect values are reported to nwscript.
Testing level received: I've checked that all plugins still compile.
> CScriptLocation and CNWSVector members need to be float

- api/CExoArrayList.h
- plugins/connect/ConnectHooks.cpp
Field meaning has been swapped.
used length comes first, array alloc size after. Not the other way round.
> api/CExoArrayList: fields named incorrectly

- modules.c
- modules.h
- newpluginapi.h
- nwnx2lib.cpp
This allows you to reuse event handlers for multiple events.
> pluginlink: GetRunningEventName() returns the current event inside hooks

- plugins/jvm/java/src/org/nwnx/nwnx2/jvm/TestRunner.java
Oversight when porting to new resman - TestRunner was still expecting old interface spec.
> plugins/jvm: make TestRunner compile new resman intf

- api/CNWSArea.cpp
- api/CNWSArea.h
- api/CNWSModule.cpp
- api/CNWSModule.h
- api/CNWSObject.cpp
- api/CNWSObject.h
Currently not used by any in-tree plugin but I'd want it upstream anyways!
> annotate api/CNWSObject|Module|Area->GetScriptVarTable() with proper type

- api/nwnstructs.h
Should be complete; field_X fields are unused alignment fillers.
> fix CNWItemProperty struct definition

- plugins/mhash/CMakeLists.txt
- plugins/mhash/NWNXMHash.cpp
- plugins/mhash/NWNXMHash.h
- plugins/mhash/apt-dep
- plugins/mhash/nwnx_mhash.nss
What the label on the tin says.
```
/**
* Generates a UUID.
*
* The UUID will be of type v4 when a reliable source of random
* data is available; otherwise, it will be a v3 bound to your local
* MAC address.
*
* See uuid_generate(3) for details.
*
* Returned value is a 36-character UUID like so:
*   2f8e8c3e-61e0-4f97-b367-b9d5c8123693
*/
string mhash_uuid();
```
> plugins/mhash: support generating UUIDs

- CMakeLists.txt
- core/core.cpp
- core/events/Module.cpp
- core/pluginlink.h
This embeds some in-function hooking. It's a bit messy but it shouldn't
conflict with any other plugins already messing with AdminLoadModule()
It also adds some static/inline helpers to do the actual hooking. We
might want to move them into a global include so every plugin can use them
but I couldn't be bothered to sort out the naming in this same PR.
Plz review thx xxxx
> core: add EVENT_CORE_MODULE_LOAD(ED|ING)

- api/CGameEffect.h
This changes:
* the Id to be the actual uint64 it is supposed to be
* the lists to be array pointers
* the duration field to be a float (this is important for newer gccs)
* LinkLeft/LinkRight are now CGameEffect*
All plugins still compile fine, however I don't know if any custom/3rd party plugins might break on the id/field_04 change.
> api: amend CGameEffect.h field types

- CMakeLists.txt
- plugins/resman/CMakeLists.txt
- plugins/statsd/CMakeLists.txt
This adds a check to pick either c++0x or c++11 depending on compiler
support. It will error out when neither standard flag is supported.
Open for discussion. :)
> make -std=c++0x the project default

- api/CNWSCreature.h
- api/CNWSObject.h
Motivation for the change is for nwnx_effects, however, the Effects fields especially are of use to a number of plugins.
> Update a few fields in CNWSObject and CNWSCreature

- core/events/Module.cpp
- include/nx_hook.h
- lib/nx_hook.c
This adds a helper function and macro to hook mid-function calls by
address and updates the usecase in core/Module.cpp.
Not sure what else to say - it's what I use all the time to grab calls
mid-function and redirect them to a local wrapper.
Basically what already happens in Module.cpp.
> NX_HOOK_CALL: helper+macro to hook mid-function calls

- CMakeLists.txt
- NWNXBase.cpp
- NWNXBase.h
- core/core.cpp
- core/events/Console.cpp
- core/events/Console_Builtins.cpp
- core/pluginlink.h
- nwnx2lib.cpp
This also handles "help" transparently so plugins can add their own
help text with minimum fuss.
Some sample commands are included.
Had to hack some global functions in to read the plugin list and
global debuglevel.
--
The helpers I had to hack in aren't all that smooth I guess. Especially not the one that adds to CNWNXBase.
Anyways, please review/discuss!
> EVENT_CORE_CONSOLE_INPUT to allow plugins handle input on the console

- plugins/gperf_gen.sh
This is just more aggressive in killing the inline hints gperf adds.
> gperf: fix generating lookup tables on c++11/newer gccs

- nwnx2lib.cpp
Because the messages on stdout are too easy to miss and I can't think of a case where continuing on when loading a plugin fails is desired.
> fail hard on plugin dlopen/dlsym

- api/nwnstructs.h
Not sure if there's a better way to do this.
```C++
STR_RES* tlkStr = new STR_RES;
g_pTlkTable->FetchInternal(myref, *tlkStr, mygender);
// Do stuff
delete tlkStr;
```
> STR_RES: flesh out fields; needed for tlk->FetchInternal

- CMakeLists.txt
- core/ThreadUtil.cpp
- core/ThreadUtil.h
- core/core.h
- core/events/Mainloop.cpp
Adds a C++ template that allows shunting code to be run in the NWN mainloop.
This is neccessary for multithreaded plugins (like network listeners, pubsub
systems, and so on).
--
**Please review and comment before merging.**
> core/: ThreadUtils helpers for easier mainloop barrier syncing

- CMakeLists.txt
This reworks the CMAKE_C_FLAGS stuff to be less obnoxious for adding new flags from command line or external config tools.
With this change applied, you can do stuff like:
```cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOUR_CFLAGS_MUST_HAVES=-Werror .```
or
```cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS=-Werror .```
Whereas before the root CMakeLists.txt always overwrote your injected changes.
> cmake: fix not accepting cflag defines from outside of cmakelists

- plugins/funcsext/funcsext_trgclk.nss
- plugins/funcsext/nwnx_funcsext.nss
changes summary:
funcsext_trgclk.nss
check validity of all objects before trying to transition
nwnx_funcsext.nss
bugfix - CreateTransitionAtLocation() invalid for waypoint and door transition types
bugfix - GetAnimation() returns nonsensical values
bugfix - names of some constants for SetScript() misspelled, resulting in syntax errors
reorganized names of SCRIPT_* constants to find more easily in script editor
corrected name of CreateTransitionOnLocation() to grammatically correct CreateTransitionAtLocation()
> nwnx_funcsext bugfixes

- plugins/odmbc/pgsql.cpp
So, yeah. Unbreak pgsql compilation on gcc 4.7.x. I know, boring.
> plugins/odmbc/pgsql: fix compile errors due to missing spaces in literal-concatenated string

- modules.c
- modules.h
- newpluginapi.h
- nwnx2lib.cpp
- plugins/jvm/NWNXJVM.cpp
- plugins/resman/DirectoryHandler.cpp
This is mostly for lazy plugin authors (like me) that want to hook
events or call services and just fail when they don't exist, because
the plugin would not work otherwise.
Best used in OnPluginsLoaded or similar - fail early and hard, like you
read about.
--
What do you think?
(In any case don't merge yet, if this is desirable I'll add optional/better error messages and warnings to the default macros too).
> pluginlink: hooking and calling helpers that exit(1) on failure

- plugins/mnx/NWNXmnx.cpp
On Ubuntu 12.04 mnx was refusing to build after picking up std::bind
a C++11 feature to bind keywords rather than the global socket call.
I'm unable to test this, but expect no issues with pinning down the scope.
> Specify global scope on call to socket bind

- plugins/events/HookFunc.cpp
- plugins/events/NWNXEvents.h
- plugins/events/nwn/nwnx_events.nss
- plugins/events/readme.txt
Hooks the devcrit feat use, allowing blocking from script. The event is only fired if:
1. Attacker is scoring a critical on the target
2. The normal critical hit damage is not enough to kill the target
3. Attacker has devastating critical feat in the weapon scoring the critical
From script, use:
```
- OBJECT_SELF        = The attacker that is using DevCrit feat
- GetEventTarget()   = Creature being hit with the devastating critical
- GetEventSubType()  = Total damage being dealt to target
- GetEventItem()     = Attacker's weapon, in which the attacker has the devcrit feat
* BypassEvent()      = Override default devastating critical handling
* SetReturnValue()   = Whether the attacker gets a cleave attack. Only valid if BypassEvent() was called.
```
I updated the readme with the script …
> Events: Devastating Critical hook and bypass

- plugins/fixes/FixesHooks.cpp
Bug, as explained by Dunshine:
> 1.69
> The -50 for dying actually works, but then you don't go unconsciout below zero anymore, that was the issue.
> So when you set it at -10, then your lose consciousness below zero, but when you change it to -50, you just stand there when between zero and -50 like nothing happened.
> The onplayerdying event just doesn't trigger anymore it seems.
The fix just updates the constant in `GetIsPCDying()`. It's hacky, but so is the existing hpLimit code, so I don't feel too bad.
The code is running on Arelith.
> fixes: hpLimit update in CNWSObject::GetIsPCDying()

- plugins/profiler/HookRunScript.cpp
This fixes offset to game area tag that is printed to the log file. Currently the area tag is garbled.
> Fixed pathfinding tag offset.
